import type { SwissKnowledgeRule } from "@/lib/insurance-knowledge/types";

/** Curated Swiss insurance knowledge for Atlas extraction context (CH). */
export const SWISS_INSURANCE_KNOWLEDGE_RULES: SwissKnowledgeRule[] = [
  {
    id: "ch-health-lamal-001",
    category: "health",
    policyType: "health",
    subtypes: ["lamal_base"],
    jurisdiction: "CH",
    sourceType: "official",
    sourceName: "LAMal / KVG",
    lastReviewed: "2026-05-24",
    ruleSummary: "Mandatory basic health covers statutory benefits, not a fixed insured sum product.",
    extractionHint:
      "LAMal/KVG base: extract franchise, aliquota/cost share, model, and person premiums from the PDF. Do not treat as RC with a massimale. Missing renewal date does not mean missing coverage.",
    userExplanation:
      "L'assicurazione base obbligatoria copre le prestazioni legalmente previste; franchigia e quota partecipazione sono partecipazione ai costi, non un massimale RC.",
    riskIfMisread: "Confusing LAMal with complementary or liability limits.",
    appliesWhen: {
      policyTypes: ["health"],
      subtypes: ["lamal_base"],
      keywords: ["lamal", "kvg", "grundversicherung", "obbligatoria", "okp", "aos"],
    },
  },
  {
    id: "ch-health-lca-001",
    category: "health",
    policyType: "health",
    subtypes: ["lca_complementary"],
    jurisdiction: "CH",
    sourceType: "official",
    sourceName: "VVG / LCA",
    lastReviewed: "2026-05-24",
    ruleSummary: "Complementary health is contractual private insurance under VVG.",
    extractionHint:
      "LCA/VVG complementary: extract product name, limits, waiting periods, and person assignment only if stated. Use policy_subtype lca_complementary or coverage_type text from PDF.",
    riskIfMisread: "Treating complementary lines as mandatory LAMal base.",
    appliesWhen: {
      policyTypes: ["health"],
      subtypes: ["lca_complementary"],
      keywords: ["lca", "vvg", "complementare", "zusatz", "complementary"],
    },
  },
  {
    id: "ch-health-cost-share-001",
    category: "health",
    policyType: "health",
    jurisdiction: "CH",
    sourceType: "official",
    sourceName: "LAMal cost participation",
    lastReviewed: "2026-05-24",
    ruleSummary: "Franchise, aliquota, and legal cost-sharing are distinct fields.",
    extractionHint:
      "Distinguish franchise (Franchise/Franchigia) from deductible/scoperto and aliquota/quota partecipazione when the PDF shows them. Extract only values present in the document.",
    riskIfMisread: "Merging franchise and aliquota into one wrong field.",
    appliesWhen: {
      policyTypes: ["health"],
      keywords: ["franchigia", "franchise", "aliquota", "quota", "selbstbehalt", "partecipazione"],
      sections: ["Premi e franchigie"],
    },
  },
  {
    id: "ch-health-premium-free-001",
    category: "health",
    policyType: "health",
    jurisdiction: "CH",
    sourceType: "internal_rule",
    sourceName: "Atlas premium list vs effective",
    lastReviewed: "2026-05-24",
    ruleSummary: "List premium and effective zero payable can coexist on complementary lines.",
    extractionHint:
      "If PDF shows listino/reference premium and premio gratuito or payable 0, set premium_gross to list and premium_final to 0. Do not invent promotion reasons not written in the PDF.",
    riskIfMisread: "Treating list price as payable or as a contradiction.",
    appliesWhen: {
      policyTypes: ["health"],
      keywords: ["gratuito", "listino", "list price", "100%", "premio 0", "totale 0"],
    },
  },
  {
    id: "ch-health-models-001",
    category: "health",
    policyType: "health",
    jurisdiction: "CH",
    sourceType: "internal_rule",
    sourceName: "Managed care models",
    lastReviewed: "2026-05-24",
    ruleSummary: "Telmed, HMO, and family-doctor models affect base insurance routing.",
    extractionHint:
      "Telmed, HMO, medico di famiglia, PREMED, or similar model names belong in model/base_insurance fields when shown. Extract exact label from PDF.",
    riskIfMisread: "Missing model constraint on base premium lines.",
    appliesWhen: {
      policyTypes: ["health"],
      keywords: ["telmed", "hmo", "premed", "medico di famiglia", "hausarzt", "gatekeeper"],
    },
  },
  {
    id: "ch-health-hospital-001",
    category: "health",
    policyType: "health",
    subtypes: ["hospital"],
    jurisdiction: "CH",
    sourceType: "internal_rule",
    sourceName: "Hospital supplementary",
    lastReviewed: "2026-05-24",
    ruleSummary: "Hospital coverage is usually supplementary, not basic LAMal alone.",
    extractionHint:
      "Hospital/spital lines (generale, semi-privata, privata): extract division type and premium per person when grouped. Use hospital subtype or descriptive coverage_type.",
    riskIfMisread: "Mislabeling hospital ward class or duplicating base lines.",
    appliesWhen: {
      policyTypes: ["health"],
      subtypes: ["hospital"],
      keywords: ["ospedal", "spital", "hospital", "semi-priv", "privat"],
    },
  },
  {
    id: "ch-health-accident-context-001",
    category: "health",
    policyType: "health",
    subtypes: ["accident"],
    jurisdiction: "CH",
    sourceType: "official",
    sourceName: "Accident in health statement",
    lastReviewed: "2026-05-24",
    ruleSummary: "Accident coverage on health statements differs from standalone LAINF.",
    extractionHint:
      "Accident/infortuni on a health premium statement: extract accident_covered per person and accident product lines under that person. Do not assume LAINF employer policy unless PDF says so.",
    riskIfMisread: "Mixing cassa-malati accident option with standalone accident insurance.",
    appliesWhen: {
      policyTypes: ["health"],
      subtypes: ["accident"],
      keywords: ["infortun", "unfall", "accident", "infortuni"],
    },
  },
  {
    id: "ch-health-age-band-001",
    category: "health",
    policyType: "health",
    jurisdiction: "CH",
    sourceType: "internal_rule",
    sourceName: "Age band labels",
    lastReviewed: "2026-05-24",
    ruleSummary: "Child/young-adult labels affect premiums but must come from PDF.",
    extractionHint:
      "Adult, child, young adult, bambino, giovane adulti labels: capture in applies_to or notes only if explicitly in PDF. Do not infer age category without evidence.",
    riskIfMisread: "Inventing child discounts or age rules not documented.",
    appliesWhen: {
      policyTypes: ["health"],
      keywords: ["bambino", "child", "giovane", "young adult", "adulto", "adult"],
    },
  },
  {
    id: "ch-accident-lainf-001",
    category: "accident_income",
    policyType: "other",
    jurisdiction: "CH",
    sourceType: "official",
    sourceName: "LAINF",
    lastReviewed: "2026-05-24",
    ruleSummary: "Standalone accident insurance (LAINF) is not the same as health LAMal.",
    extractionHint:
      "LAINF/UVG accident policy: extract insured persons, sums, and premiums from PDF. Use policy_type other and descriptive policy_category_label; do not classify as health LAMal.",
    riskIfMisread: "Classifying employer accident policy as cassa malati.",
    appliesWhen: {
      keywords: ["lainf", "uvg", "infortuni professionali", "assicurazione infortuni"],
    },
  },
  {
    id: "ch-accident-igm-001",
    category: "accident_income",
    policyType: "other",
    subtypes: ["income_protection"],
    jurisdiction: "CH",
    sourceType: "official",
    sourceName: "Daily sickness allowance",
    lastReviewed: "2026-05-24",
    ruleSummary: "IGM covers daily allowance during illness, not base health.",
    extractionHint:
      "Indennita giornaliera malattia / Krankentaggeld: extract daily benefit, waiting period, and duration limits from PDF only.",
    riskIfMisread: "Confusing IGM with LAMal or accident lump sums.",
    appliesWhen: {
      subtypes: ["income_protection"],
      keywords: ["indennita giornaliera", "taggeld", "krankentaggeld", "igm"],
    },
  },
  {
    id: "ch-accident-ipg-001",
    category: "accident_income",
    policyType: "other",
    subtypes: ["income_protection"],
    jurisdiction: "CH",
    sourceType: "official",
    sourceName: "Income protection / disability",
    lastReviewed: "2026-05-24",
    ruleSummary: "Private disability/income protection has insured pension amounts.",
    extractionHint:
      "Incapacita di guadagno / invalidita / Erwerbsausfall: extract insured pension or capital amounts and waiting periods from PDF. Use income_protection subtype or textual category.",
    riskIfMisread: "Missing disability capital or confusing with IGM daily allowance.",
    appliesWhen: {
      keywords: ["incapacita", "invalidita", "erwerbsausfall", "perdita di guadagno", "disability"],
    },
  },
  {
    id: "ch-liability-rc-001",
    category: "liability_household",
    policyType: "liability",
    subtypes: ["liability"],
    jurisdiction: "CH",
    sourceType: "official",
    sourceName: "Private RC",
    lastReviewed: "2026-05-24",
    ruleSummary: "Private RC covers third-party liability with a sum insured.",
    extractionHint:
      "RC privata: extract liability_limit/massimale, deductible, and insured household members from PDF. Coverage is toward third parties, not own property damage.",
    riskIfMisread: "Confusing RC with household contents or auto RC.",
    appliesWhen: {
      policyTypes: ["liability"],
      subtypes: ["liability"],
      keywords: ["rc privata", "privathaftpflicht", "responsabilita civile"],
    },
  },
  {
    id: "ch-household-ed-001",
    category: "liability_household",
    policyType: "household",
    subtypes: ["household"],
    jurisdiction: "CH",
    sourceType: "internal_rule",
    sourceName: "Household contents",
    lastReviewed: "2026-05-24",
    ruleSummary: "Household insurance covers movables at insured location.",
    extractionHint:
      "Economia domestica / Hausrat: extract insured_sum, location if stated, theft/fire/water/glass flags, and deductible from PDF only.",
    riskIfMisread: "Applying household rules to buildings or vehicles.",
    appliesWhen: {
      policyTypes: ["household"],
      subtypes: ["household"],
      keywords: ["economia domestica", "mobilia", "hausrat", "menage", "household"],
    },
  },
  {
    id: "ch-household-building-001",
    category: "liability_household",
    policyType: "other",
    jurisdiction: "CH",
    sourceType: "internal_rule",
    sourceName: "Buildings vs contents",
    lastReviewed: "2026-05-24",
    ruleSummary: "Building/stabili cover is not household movables.",
    extractionHint:
      "Fabbricato / stabili / Gebaude: use policy_type other with building label in policy_category_label. Extract sums and perils from PDF; do not map to household insured_sum without evidence.",
    riskIfMisread: "Mixing building shell with contents insurance.",
    appliesWhen: {
      keywords: ["fabbricato", "stabili", "gebaude", "building", "immobile"],
    },
  },
  {
    id: "ch-household-valuables-001",
    category: "liability_household",
    policyType: "household",
    jurisdiction: "CH",
    sourceType: "internal_rule",
    sourceName: "Valuables extensions",
    lastReviewed: "2026-05-24",
    ruleSummary: "Bikes, devices, and valuables may be sub-limits or extensions.",
    extractionHint:
      "Bicicletta, oggetti di valore, gioielli, elettronica: extract as separate coverages or notes only if listed in PDF with sums or sub-limits.",
    riskIfMisread: "Ignoring sub-limits on valuables.",
    appliesWhen: {
      policyTypes: ["household", "other"],
      keywords: ["bicicletta", "bike", "gioielli", "valori", "oggetti", "electronic", "velo"],
    },
  },
  {
    id: "ch-vehicle-rc-001",
    category: "vehicle",
    policyType: "car",
    subtypes: ["car"],
    jurisdiction: "CH",
    sourceType: "official",
    sourceName: "Motor liability",
    lastReviewed: "2026-05-24",
    ruleSummary: "Motor third-party liability is mandatory in Switzerland.",
    extractionHint:
      "RC auto / MF: extract plate_number, vehicle identifiers, and liability coverage from PDF. Mandatory RC is not optional casco.",
    riskIfMisread: "Treating RC auto as household RC or omitting plate.",
    appliesWhen: {
      policyTypes: ["car"],
      keywords: ["rc auto", "motorfahrzeug", "haftpflicht", "assicurazione auto", "targa"],
    },
  },
  {
    id: "ch-vehicle-casco-001",
    category: "vehicle",
    policyType: "car",
    subtypes: ["casco_partial", "casco_full"],
    jurisdiction: "CH",
    sourceType: "internal_rule",
    sourceName: "Casco partial and full",
    lastReviewed: "2026-05-24",
    ruleSummary: "Partial and full casco are optional damage covers.",
    extractionHint:
      "Casco parziale/teilkasko vs casco totale/vollkasko: extract casco field and deductibles separately. Use subtypes casco_partial/casco_full when clear from PDF.",
    riskIfMisread: "Merging partial and full casco or inventing insured vehicle value.",
    appliesWhen: {
      policyTypes: ["car"],
      subtypes: ["casco_partial", "casco_full"],
      keywords: ["casco", "teilkasko", "vollkasko", "kasko", "collision"],
    },
  },
  {
    id: "ch-vehicle-bonus-001",
    category: "vehicle",
    policyType: "car",
    jurisdiction: "CH",
    sourceType: "internal_rule",
    sourceName: "Bonus malus",
    lastReviewed: "2026-05-24",
    ruleSummary: "Bonus-malus class affects premium but must be extracted from PDF.",
    extractionHint:
      "Bonus/malus or bonus-malus level: map to bonus_malus field when stated. Do not infer class from premium amount alone.",
    riskIfMisread: "Inventing bonus class or franchise not shown.",
    appliesWhen: {
      policyTypes: ["car"],
      keywords: ["bonus", "malus", "bonus-malus", "pramie"],
    },
  },
  {
    id: "ch-vehicle-assistance-001",
    category: "vehicle",
    policyType: "car",
    jurisdiction: "CH",
    sourceType: "internal_rule",
    sourceName: "Roadside assistance",
    lastReviewed: "2026-05-24",
    ruleSummary: "Assistance is an optional add-on, not RC.",
    extractionHint:
      "Assistenza / soccorso / breakdown: extract as coverage line or notes if present. Do not conflate with casco or RC.",
    riskIfMisread: "Missing assistance module or mislabeling as casco.",
    appliesWhen: {
      policyTypes: ["car"],
      keywords: ["assistenza", "soccorso", "assistance", "pannenhilfe", "breakdown"],
    },
  },
  {
    id: "ch-legal-private-001",
    category: "legal_travel_personal",
    policyType: "legal",
    subtypes: ["legal_protection"],
    jurisdiction: "CH",
    sourceType: "internal_rule",
    sourceName: "Private legal protection",
    lastReviewed: "2026-05-24",
    ruleSummary: "Private legal protection covers legal expenses in private disputes.",
    extractionHint:
      "Protezione giuridica privata: set private_legal true when PDF indicates private coverage; extract waiting periods, insured persons, and caps from document only.",
    riskIfMisread: "Confusing private with traffic legal protection.",
    appliesWhen: {
      policyTypes: ["legal"],
      subtypes: ["legal_protection"],
      keywords: ["protezione giuridica", "rechtsschutz", "protection juridique", "privat"],
    },
  },
  {
    id: "ch-legal-traffic-001",
    category: "legal_travel_personal",
    policyType: "legal",
    jurisdiction: "CH",
    sourceType: "internal_rule",
    sourceName: "Traffic legal protection",
    lastReviewed: "2026-05-24",
    ruleSummary: "Traffic legal protection is distinct from private legal.",
    extractionHint:
      "Giuridica circolazione / Verkehrsrechtsschutz: set traffic_legal when stated. Extract exclusions and territorial scope from PDF.",
    riskIfMisread: "Marking traffic module as private legal only.",
    appliesWhen: {
      policyTypes: ["legal"],
      keywords: ["circolazione", "verkehr", "traffic", "strada", "mobilita"],
    },
  },
  {
    id: "ch-travel-001",
    category: "legal_travel_personal",
    policyType: "other",
    subtypes: ["travel"],
    jurisdiction: "CH",
    sourceType: "internal_rule",
    sourceName: "Travel insurance",
    lastReviewed: "2026-05-24",
    ruleSummary: "Travel policies cover trip-related risks, not home RC.",
    extractionHint:
      "Viaggio / travel / annullamento: use travel subtype or policy_category_label from PDF. Extract trip cancellation, medical abroad, and baggage only if listed.",
    riskIfMisread: "Classifying travel as health LAMal or household.",
    appliesWhen: {
      subtypes: ["travel"],
      keywords: ["viaggio", "travel", "reise", "annullamento", "bagaglio"],
    },
  },
  {
    id: "ch-personal-pet-cyber-001",
    category: "legal_travel_personal",
    policyType: "other",
    jurisdiction: "CH",
    sourceType: "internal_rule",
    sourceName: "Pet and personal cyber",
    lastReviewed: "2026-05-24",
    ruleSummary: "Pet and personal cyber are contractual specialty products.",
    extractionHint:
      "Animali domestici / pet / cyber personale: use policy_type other and descriptive policy_category_label from PDF. Extract limits and exclusions only when written.",
    riskIfMisread: "Forcing into household or legal templates.",
    appliesWhen: {
      keywords: ["animali", "pet", "cyber", "domestici", "cane", "gatto"],
    },
  },
  {
    id: "ch-life-risk-001",
    category: "life_pension",
    policyType: "other",
    subtypes: ["life"],
    jurisdiction: "CH",
    sourceType: "internal_rule",
    sourceName: "Risk life insurance",
    lastReviewed: "2026-05-24",
    ruleSummary: "Risk life pays on death; savings/mixed have different structures.",
    extractionHint:
      "Vita rischio / death benefit: extract insured capital, beneficiaries, premium, and term from PDF. Use life subtype and textual labels for product type.",
    riskIfMisread: "Confusing risk life with pure savings or pension wrappers.",
    appliesWhen: {
      subtypes: ["life"],
      keywords: ["vita", "life", "decesso", "death", "capitale", "beneficiar"],
    },
  },
  {
    id: "ch-life-3a-001",
    category: "life_pension",
    policyType: "other",
    jurisdiction: "CH",
    sourceType: "official",
    sourceName: "Pillar 3a insurance",
    lastReviewed: "2026-05-24",
    ruleSummary: "3a insurance policies have pension/tax wrapper context.",
    extractionHint:
      "Previdenza 3a / pilastro 3a: capture in policy_category_label or notes when PDF states 3a. Extract premium, duration, surrender value only if explicitly shown.",
    riskIfMisread: "Inventing tax advantages or 3a eligibility not in document.",
    appliesWhen: {
      keywords: ["3a", "pilastro", "previdenza", "pillar", "saeule 3a"],
    },
  },
  {
    id: "ch-life-mixed-001",
    category: "life_pension",
    policyType: "other",
    subtypes: ["life"],
    jurisdiction: "CH",
    sourceType: "internal_rule",
    sourceName: "Mixed/savings life",
    lastReviewed: "2026-05-24",
    ruleSummary: "Mixed life combines risk and savings components.",
    extractionHint:
      "Vita mista / risparmio / savings component: separate death capital and surrender/account value fields only when PDF distinguishes them.",
    riskIfMisread: "Single premium field hiding savings vs risk split.",
    appliesWhen: {
      subtypes: ["life"],
      keywords: ["mista", "risparmio", "savings", "survival", "riscatto", "surrender"],
    },
  },
  {
    id: "ch-business-rc-001",
    category: "business",
    policyType: "other",
    subtypes: ["business"],
    jurisdiction: "CH",
    sourceType: "internal_rule",
    sourceName: "Business liability",
    lastReviewed: "2026-05-24",
    ruleSummary: "Business RC covers company liability, not private RC.",
    extractionHint:
      "RC aziendale / betriebshaftpflicht: policy_type other, business label. Extract company name, activity, and liability sums from PDF. Do not apply private RC household rules.",
    riskIfMisread: "Classifying SME RC as private liability.",
    appliesWhen: {
      subtypes: ["business"],
      keywords: ["aziend", "business", "betrieb", "rc aziendale", "impresa"],
    },
  },
  {
    id: "ch-business-property-001",
    category: "business",
    policyType: "other",
    subtypes: ["business"],
    jurisdiction: "CH",
    sourceType: "internal_rule",
    sourceName: "Business property",
    lastReviewed: "2026-05-24",
    ruleSummary: "Business property covers company assets, not home movables.",
    extractionHint:
      "Assicurazione cose aziendali / inventario / stock: extract location, sums, and perils from PDF. Use generic_details or coverages[] with business labels.",
    riskIfMisread: "Mapping business inventory to household insured_sum.",
    appliesWhen: {
      subtypes: ["business"],
      keywords: ["cose aziendali", "inventario", "stock", "betriebsinventar", "property"],
    },
  },
  {
    id: "ch-business-interruption-001",
    category: "business",
    policyType: "other",
    jurisdiction: "CH",
    sourceType: "internal_rule",
    sourceName: "Business interruption",
    lastReviewed: "2026-05-24",
    ruleSummary: "Business interruption is indemnity for lost earnings.",
    extractionHint:
      "Perdita d esercizio / business interruption: extract waiting period, indemnity period, and sums only from PDF text.",
    riskIfMisread: "Confusing with IGM or household claims.",
    appliesWhen: {
      keywords: ["perdita", "esercizio", "interruption", "betriebsunterbruch"],
    },
  },
  {
    id: "ch-business-cyber-001",
    category: "business",
    policyType: "other",
    subtypes: ["business"],
    jurisdiction: "CH",
    sourceType: "internal_rule",
    sourceName: "Business cyber",
    lastReviewed: "2026-05-24",
    ruleSummary: "Business cyber covers company IT/incident response.",
    extractionHint:
      "Cyber aziendale: policy_type other with cyber business label. Extract limits, incident response, and exclusions from PDF only.",
    riskIfMisread: "Applying personal cyber rules to SME policies.",
    appliesWhen: {
      keywords: ["cyber", "ransomware", "data breach", "it sicurezza"],
    },
  },
];
